volumes:
  postgres_data:

services:
  db: #=#=#=#=#=# DB #=#=#=#=#=#
    image: postgres:15-alpine
    container_name: legallens_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: legallens_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck: # Como un flag (https://docs.docker.com/compose/how-tos/startup-order/)
      test: [ "CMD-SHELL", "pg_isready -U admin -d legallens_db" ]
      interval: 5s  # Segundos para realizar un check
      timeout: 5s   # Falla el check si el pg_isready tarda mas de estos segundos
      retries: 24   # Dos minutos ( 24 intentos en intervalos de 5 segundos

  backend-django: #=#=#=#=#=# DJANGO #=#=#=#=#=#
    build: ./backend
    container_name: backend-django-legallens
    env_file:
      - .env
    depends_on:
      - db
    expose: # 'expose' en vez de 'ports' hace que solo sea accesible internamente para Nginx
      - "8080"
    volumes:
      - ./backend:/app
    # Comando de arranque en Dockerfile propio (./backend/Dockerfile)


  ai-engine: #=#=#=#=#=# FASTAPI #=#=#=#=#=#
    build: ./ai_engine
    container_name: fastapi-ai-engine
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy # Checkea la condicion "healty" que tiene el contenedor de db
    expose: # 'expose' en vez de 'ports' hace que solo sea accesible internamente para Nginx
      - "8000"
    volumes:
      - ./ai_engine:/app
    # Comando de arranque en Dockerfile propio (./ai_engine/Dockerfile)


  nginx: #=#=#=#=#=# NGINX #=#=#=#=#=#
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend-django
      - ai-engine
