# Generated by Django 6.0.4 on 2026-04-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_legallens', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='user',
            new_name='lawyer',
        ),
        migrations.AlterField(
            model_name='auditresult',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditresult',
            name='red_flags',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='auditresult',
            name='risk_level',
            field=models.CharField(choices=[('none', 'Nada'), ('low', 'Bajo'), ('medium', 'Medio'), ('high', 'Alto')]),
        ),
    ]
